apiVersion: kcl.evrone.com/v1alpha1
kind: KclInstance
metadata:
  name: kcl-instance-v1
  namespace: default
spec:
  path: examples/appops/nginx-example/dev
  interval: 20s
  sourceRef:
    kind: GitRepository
    name: konfig-akirill0v
    namespace: default
  config:
    vendor: true
    sortKeys: true
    showHidden: true
    arguments:
      env: dev
      baz: qux
    argumentsFrom:
      - name: kcl-instance-config
        kind: ConfigMap
        argumentsKey: arguments.yaml
        targetPath: spec.instanceConfig.arguments
        optional: true
